In [1]:
# NumPy -> Numerical Python
'''
Mathematical Calculation

Python List -> [] -> Data Store

NumPy -> [] -> NumPy Array
'''

'\nMathematical Calculation\n\nPython List -> [] -> Data Store\n\nNumPy -> [] -> NumPy Array\n'

In [2]:
num1 = [1, 2, 3, 4] # 1 X 4
num2 = [5, 6, 7, 8] # 1 X 4
num3 = num1 + num2
print(num3)

[1, 2, 3, 4, 5, 6, 7, 8]


In [1]:
# To use NumPy we have to import NumPy Package / Module.
import numpy as np

In [4]:
num1_array = np.array(num1)
num2_array = np.array(num2)

num3_arr = num1_array + num2_array
num3_arr

array([ 6,  8, 10, 12])

In [5]:
type(num1_array)

numpy.ndarray

# 1D and 2/Multi-D Array

In [6]:
array_1d = np.array([6, 8, 10, 12])
array_1d

array([ 6,  8, 10, 12])

In [7]:
array_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
array_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
array_2d.shape # shape of matrix

(3, 4)

In [9]:
array_2d.size # total number of times in an array

12

In [10]:
array_2d.ndim # show dimension of an array

2

In [11]:
array_1d.ndim

1

In [12]:
array_1d.shape

(4,)

# Zeros and Ones

In [13]:
# zeros(shape, dtype=float(default)/int)
zeros_one = np.zeros(4, dtype=int)
zeros_one

array([0, 0, 0, 0])

In [14]:
zeros_two = np.zeros((4, 3), dtype=int)
zeros_two

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
one_one = np.ones(4, dtype=int)
one_one

array([1, 1, 1, 1])

In [16]:
one_two = np.ones((4, 3), dtype=int)
one_two

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# Arange

In [18]:
# for i in range(1, 11):
#     print(i)

In [4]:
numbers = np.arange(1, 61)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [5]:
numbers.shape

(60,)

In [21]:
num = []
for i in range(1, 11):
     num.append(i)
num = np.array(num)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Reshape and Ravel

In [ ]:
'''
Reshape -> convert any dimension of array into desired array format we want.
        -> We cannot do reshape array which has prime set of values.

Ravel -> Convery any dimenion of array into 1D array
'''

In [6]:
reshape_numbers = numbers.reshape(10, 6)
reshape_numbers

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [28]:
reshape_numbers.shape

(6, 10)

In [29]:
ravel_numbers = reshape_numbers.ravel()
ravel_numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [30]:
reshape_numbers

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [32]:
ravel_numbers[2:6]

array([3, 4, 5, 6])

In [34]:
# arr[row, columns]
reshape_numbers[1:3, 2:4]

array([[13, 14],
       [23, 24]])

# Array Broadcasting

In [ ]:
'''
Rules of Broadcasting
------------------------
1. For calculation all dimension of array's shape must be same/equal.
2. Any shape of array row or column must be 1 and other must be equal.
'''

In [7]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]) # 3 X 4

In [20]:
arr2 = np.array([
    [13, 14, 15, 16],
    [17, 18, 19, 20],
    [21, 22, 23, 24]
]) # 3 X 4

In [21]:
add = arr + arr2
add

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

# Boolean Indexing

In [53]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [24]:
# Find all the numbers which is greater than 50.
filter_numbers = numbers > 50
numbers[filter_numbers]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [56]:
fruits = np.array(["Apple", "Banana", "Coconut", "Apple", "Apple"])
fruits

array(['Apple', 'Banana', 'Coconut', 'Apple', 'Apple'], dtype='<U7')

In [57]:
filter_fruits = fruits == 'Apple'
fruits[filter_fruits]

array(['Apple', 'Apple', 'Apple'], dtype='<U7')

In [ ]:
# meshgrid